spring.application.name=DendroApp

# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/dendroapp?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Jedinstvo24022024.

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.access=DEBUG


# Backend port
server.port=${PORT:8080}

jwt.secret=1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z7a8b9c0d1e2f






























































